Task 8
Garanyan/made pull request #7
Opened 2019-11-23 11:43 UTC by Garanyan

https://contest.yandex.ru/contest/15369/run-report/26797974/

2019-12-01 13:09 UTC, smatskevich requested changes
Немного замечаний. Поправьте, пожалуйста.

2019-12-01 13:09 UTC, smatskevich commented on Algorithms/task_8.cpp
> +    std::vector<HashTableNode *> table;
Не надо хранить vector<HashTableNode*> - так много аллокаций. Лучше vector<HashTableNode> - память существенно сэкономите и не будет фрагментации.
А еще лучше `vector<std::string> `

2019-12-01 13:09 UTC, smatskevich commented on Algorithms/task_8.cpp
> +unsigned int HashTable::firstHash(const std::string &str) const{
Метод должен быть статическим

2019-12-01 13:09 UTC, smatskevich commented on Algorithms/task_8.cpp
> +}
Оставляйте перевод строки в конце файла. Потом при добавлении последняя строка не попадет в будущий diff.

2019-12-08 09:02 UTC, Garanyan commented on Algorithms/task_8.cpp
> +unsigned int HashTable::firstHash(const std::string &str) const{
метод не может быть статическим, т.к. вызывает функцию hornerHash, которая зависит от размера таблицы

2019-12-14 22:39 UTC, smatskevich requested changes
Извините за задержку.
Теперь не проходят тесты - TimeLimit на последнем тесте.

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +unsigned int HashTable::firstHash(const std::string &str) const{
Ok

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +    auto prevTable = table;
std::move

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +    table = newTable;
std::move

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +    for(size_t hash = firstHash(key), i = 1;
size_t hash = startHash;

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +        if(table[hash].empty() && !removed[hash])
Это можно вызвать до сравнения строк

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +    std::string new_node;
new_node - лишняя переменная. Лучше использовать new_node_hash для проверки, нашли ли место вставки.

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +    } while(hash != startHash);
Здесь надо бы также ограничить число просмотров - размером таблицы.

2019-12-14 22:39 UTC, smatskevich commented on Algorithms/task_8.cpp
> +        !table[hash].empty() || removed[hash]; hash = (startHash + i * shift) % table.size(), i++){
Надо бы ограничить число просмотров размером таблицы.

2019-12-21 22:17 UTC, smatskevich requested changes
Runtime error на третьем тесте.

2019-12-22 07:34 UTC, Garanyan commented
Исправил
https://contest.yandex.ru/contest/15369/run-report/29166760/

2019-12-22 14:15 UTC, smatskevich approved these changes
Принято.

2019-12-23 13:31 UTC, merged